name: SILVIA MAZZARRI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08599
title: 'Me & Light'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#b8b5ac'
    - '#5f5f5f'
    - '#919191'
    - '#22231d'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
