name: SILVIA MAZZARRI
favicon: null
layout_spectrum: 0.33236
typography_spectrum: 0.3595
title: 'Me & Light'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090502'
    - '#4d4a3c'
    - '#908d7b'
    - '#fdc13b'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
