name: SILVIA MAZZARRI
favicon: null
layout_spectrum: 0.4991218114737421
typography_spectrum: 0.43095398833975196
title: 'Me & Light'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9612379160244018
  lightness: 0.6287393127568066
  saturation: 0.2048610111232847
  rhythmicContrast: 0.38553542690351605
purpose: []
